<?php

namespace app\modules\admin\controllers;

use yii\web\Controller;
use Yii;
use yii\helpers\Url;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{

    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest) {
            return Yii::$app->getResponse()->redirect(Url::to(['/admin/site/login']), 302);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
    	
//        return $this->render('index');
//        $item = Project::find();
        $model = Yii::$app->user->identity;
//    	return $this->redirect('user/user');
//        var_dump($item); die();
        return $this->render('index',[
            'model'=>$model,
//            'item'=>$item

        ]);

    }

    public function actionLogin()
    {
    	return $this->render('login');
    }
}
